// Generated by js_of_ocaml 2.5
(function(s){"use strict";var
P=224,q=1024,M=57343,O=512,d=128,e="",L="car.reads: ",z=" : file already exists",I=2048,J=56320,K=240,a=248,H="/",N="fd ";function
ag(){var
b=s.console?s.console:{},c=["log","debug","info","warn","error","assert","dir","dirxml","trace","group","groupCollapsed","groupEnd","time","timeEnd"];function
d(){}for(var
a=0;a<c.length;a++)if(!b[c[a]])b[c[a]]=d;return b}function
U(a){if(a.length<24){for(var
b=0;b<a.length;b++)if(a.charCodeAt(b)>127)return false;return true}else
return!/[^\x00-\x7f]/.test(a)}function
aw(a){for(var
j=e,c=j,b,l,h=0,k=a.length;h<k;h++){b=a.charCodeAt(h);if(b<d){for(var
i=h+1;i<k&&(b=a.charCodeAt(i))<d;i++);if(i-h>O){c.substr(0,1);j+=c;c=e;j+=a.slice(h,i)}else
c+=a.slice(h,i);if(i==k)break;h=i}if(b<I){c+=String.fromCharCode(192|b>>6);c+=String.fromCharCode(d|b&63)}else
if(b<55296||b>=M)c+=String.fromCharCode(P|b>>12,d|b>>6&63,d|b&63);else
if(b>=56319||h+1==k||(l=a.charCodeAt(h+1))<J||l>M)c+="\xef\xbf\xbd";else{h++;b=(b<<10)+l-56613888;c+=String.fromCharCode(K|b>>18,d|b>>12&63,d|b>>6&63,d|b&63)}if(c.length>q){c.substr(0,1);j+=c;c=e}}return j+c}function
aq(a,b){if(b.repeat)return b.repeat(a);var
c=e,d=0;if(a==0)return c;for(;;){if(a&1)c+=b;a>>=1;if(a==0)return c;b+=b;d++;if(d==9)b.slice(0,1)}}function
az(a,b,c){var
e=new
Array(c);for(var
d=0;d<c;d++)e[d]=a[b+d];return e}function
C(a,b,c){var
d=String.fromCharCode;if(b==0&&c<=4096&&c==a.length)return d.apply(null,a);var
h=e;for(;0<c;b+=q,c-=q)h+=d.apply(null,az(a,b,Math.min(c,q)));return h}function
S(a){if(a.t==2)a.c+=aq(a.l-a.c.length,"\0");else
a.c=C(a.c,0,a.c.length);a.t=0}function
av(a){for(var
n=e,h=e,k,j,l,b,c=0,m=a.length;c<m;c++){j=a.charCodeAt(c);if(j<d){for(var
i=c+1;i<m&&(j=a.charCodeAt(i))<d;i++);if(i-c>O){h.substr(0,1);n+=h;h=e;n+=a.slice(c,i)}else
h+=a.slice(c,i);if(i==m)break;c=i}b=1;if(++c<m&&((l=a.charCodeAt(c))&-64)==d){k=l+(j<<6);if(j<P){b=k-12416;if(b<d)b=1}else{b=2;if(++c<m&&((l=a.charCodeAt(c))&-64)==d){k=l+(k<<6);if(j<K){b=k-925824;if(b<I||b>=55295&&b<57344)b=2}else{b=3;if(++c<m&&((l=a.charCodeAt(c))&-64)==d&&j<245){b=l-63447168+(k<<6);if(b<65536||b>1114111)b=3}}}}}if(b<4){c-=b;h+="\ufffd"}else
if(b>65535)h+=String.fromCharCode(55232+(b>>10),J+(b&1023));else
h+=String.fromCharCode(b);if(h.length>q){h.substr(0,1);n+=h;h=e}}return n+h}function
au(a){switch(a.t){case
9:return a.c;default:S(a);case
0:if(U(a.c)){a.t=9;return a.c}a.t=8;case
8:return av(a.c)}}function
k(a,b,c){this.t=a;this.c=b;this.l=c}k.prototype={toString:function(){return au(this)}};function
V(a){var
b=9;if(!U(a))b=8,a=aw(a);return new
k(b,a,a.length)}function
an(a,b){throw[0,a,b]}function
c(a){return new
k(0,a,a.length)}function
Y(a,b){an(a,c(b))}var
h=[0];function
j(a){Y(h[2],a)}function
ah(a){if(!a.opened)j("Cannot flush a closed channel");if(a.buffer==e)return 0;if(a.output)switch(a.output.length){case
2:a.output(a,a.buffer);break;default:a.output(a.buffer)}a.buffer=e;return 0}function
T(a){Y(h[4],a)}function
o(a){if(a<0)T("String.create");return new
k(a?2:9,e,a)}function
l(a){this.data=a}l.prototype={truncate:function(){this.data=o(0)}};function
B(a){return a.l}function
X(a){a=a
instanceof
k?a.toString():a;j(a+": No such file or directory")}var
ae=H;function
t(a){a=a
instanceof
k?a.toString():a;if(a.charCodeAt(0)!=47)a=ae+a;var
d=a.split(H),b=[];for(var
c=0;c<d.length;c++)switch(d[c]){case"..":if(b.length>1)b.pop();break;case".":break;case"":if(b.length==0)b.push(e);break;default:b.push(d[c]);break}b.orig=a;return b}function
m(){this.content={}}m.prototype={exists:function(a){return this.content[a]?1:0},mk:function(a,b){this.content[a]=b},get:function(a){return this.content[a]},list:function(){var
a=[];for(var
b
in
this.content)a.push(b);return a},remove:function(a){delete
this.content[a]}};var
v=new
m();v.mk(e,new
m());function
A(a){var
b=v;for(var
c=0;c<a.length;c++){if(!(b.exists&&b.exists(a[c])))X(a.orig);b=b.get(a[c])}return b}function
at(a){var
c=t(a),b=A(c);return b
instanceof
m?1:0}function
ar(a){return new
k(4,a,a.length)}function
R(a){var
c=new
Array(a.l),e=a.c,d=e.length,b=0;for(;b<d;b++)c[b]=e.charCodeAt(b);for(d=a.l;b<d;b++)c[b]=0;a.c=c;a.t=4;return c}function
aA(a){if(a.t!=4)R(a);return a.c}function
af(a,b){var
h=t(a),d=v;for(var
i=0;i<h.length-1;i++){var
e=h[i];if(!d.exists(e))d.mk(e,new
m());d=d.get(e);if(!(d
instanceof
m))j(h.orig+z)}var
e=h[h.length-1];if(d.exists(e))j(h.orig+z);if(b
instanceof
m)d.mk(e,b);else
if(b
instanceof
l)d.mk(e,b);else
if(b
instanceof
k)d.mk(e,new
l(b));else
if(b
instanceof
Array)d.mk(e,new
l(ar(b)));else
if(b.toString)d.mk(e,new
l(c(b.toString())));else
T("caml_fs_register");return 0}function
as(a){var
b=v,d=t(a),e,h;for(var
c=0;c<d.length;c++){if(b.auto){e=b.auto;h=c}if(!(b.exists&&b.exists(d[c])))return e?e(d,h):0;b=b.get(d[c])}return 1}function
r(a,b,c){if(h.fds===undefined)h.fds=new
Array();c=c?c:{};var
d={};d.file=b;d.offset=c.append?B(b.data):0;d.flags=c;h.fds[a]=d;h.fd_last_idx=a;return a}function
aB(a,b,c){var
d={};while(b){switch(b[1]){case
0:d.rdonly=1;break;case
1:d.wronly=1;break;case
2:d.append=1;break;case
3:d.create=1;break;case
4:d.truncate=1;break;case
5:d.excl=1;break;case
6:d.binary=1;break;case
7:d.text=1;break;case
8:d.nonblock=1;break}b=b[2]}var
i=a.toString(),l=t(a);if(d.rdonly&&d.wronly)j(i+" : flags Open_rdonly and Open_wronly are not compatible");if(d.text&&d.binary)j(i+" : flags Open_text and Open_binary are not compatible");if(as(a)){if(at(a))j(i+" : is a directory");if(d.create&&d.excl)j(i+z);var
k=h.fd_last_idx?h.fd_last_idx:0,e=A(l);if(d.truncate)e.truncate();return r(k+1,e,d)}else
if(d.create){var
k=h.fd_last_idx?h.fd_last_idx:0;af(a,o(0));var
e=A(l);return r(k+1,e,d)}else
X(a)}r(0,new
l(o(0)));r(1,new
l(o(0)));r(2,new
l(o(0)));function
ai(a){var
b=h.fds[a];if(b.flags.wronly)j(N+a+" is writeonly");return{file:b.file,offset:b.offset,fd:a,opened:true}}function
Q(a,b,c,d,e){if(e==0)return 0;if(d==0&&(e>=c.l||c.t==2&&e>=c.c.length)){c.c=a.t==4?C(a.c,b,e):b==0&&a.c.length==e?a.c:a.c.substr(b,e);c.t=c.c.length==c.l?0:2}else
if(c.t==2&&d==c.c.length){c.c+=a.t==4?C(a.c,b,e):b==0&&a.c.length==e?a.c:a.c.substr(b,e);c.t=c.c.length==c.l?0:2}else{if(c.t!=4)R(c);var
i=a.c,j=c.c;if(a.t==4)for(var
h=0;h<e;h++)j[d+h]=i[b+h];else{var
k=Math.min(e,i.length-b);for(var
h=0;h<k;h++)j[d+h]=i.charCodeAt(b+h);for(;h<e;h++)j[d+h]=0}}return 0}function
ax(a){if(a.charCodeAt(a.length-1)==10)a=a.substr(0,a.length-1);var
b=s.console;b&&b.error&&b.error(a)}function
ay(a){if(a.charCodeAt(a.length-1)==10)a=a.substr(0,a.length-1);var
b=s.console;b&&b.log&&b.log(a)}var
u=new
Array();function
ap(a,b){var
j=c(b),d=B(j),i=B(a.file.data),h=a.offset;if(h+d>=i){var
e=o(h+d);Q(a.file.data,0,e,0,i);Q(j,0,e,h,d);a.file.data=e}a.offset+=d;return 0}function
W(a){var
b;switch(a){case
1:b=ay;break;case
2:b=ax;break;default:b=ap}var
d=h.fds[a];if(d.flags.rdonly)j(N+a+" is readonly");var
c={file:d.file,offset:d.offset,fd:a,opened:true,buffer:e,output:b};u[c.fd]=c;return c}function
aj(){var
a=0;for(var
b
in
u)if(u[b].opened)a=[0,u[b],a];return a}function
al(a){return a
instanceof
Array?a[0]:a
instanceof
k?252:1e3}function
b(a,b){h[a+1]=b}var
ak={};function
ad(a){if((a.t&6)!=0)S(a);return a.c}function
ao(a,b){ak[ad(a)]=b;return 0}var
am=0;function
p(a){a[2]=am++;return a}b(11,[a,c("Undefined_recursive_module"),-12]);b(10,[a,c("Assert_failure"),-11]);b(9,[a,c("Sys_blocked_io"),-10]);b(8,[a,c("Stack_overflow"),-9]);b(7,[a,c("Match_failure"),-8]);b(6,[a,c("Not_found"),-7]);b(5,[a,c("Division_by_zero"),-6]);b(4,[a,c("End_of_file"),-5]);b(3,[a,c("Invalid_argument"),-4]);b(2,[a,c("Failure"),-3]);b(1,[a,c("Sys_error"),-2]);b(0,[a,c("Out_of_memory"),-1]);p([a,c("Pervasives.Exit"),0]);ai(0);W(1);W(2);p([a,c("Array.Bottom"),0]);p([a,c("Sys.Break"),0]);p([a,c("CamlinternalFormat.Type_mismatch"),0]);var
D=[0,0],ab=c("Js.Error"),ac=c("Dom_html.Canvas_not_available");function
E(a){D[1]=[0,a,D[1]];return 0}var
w=s,aa=w.Array,F=p([a,ab,0]),y=[0,F,{}],$=undefined,_=al(y)===a?y:y[0+1];ao(c("jsError"),_);E(function(a){return a[1]===F?[0,V(a[2].toString())]:0});E(function(a){return a
instanceof
aa?0:[0,V(a.toString())]});p([a,ac,0]);w.HTMLElement===$;var
i=ag(0);i.log("Console message from ocaml");w.alert("Alert window from ocaml");i.log("x: ",x);i.log("f()",f());i.log("g(3)",g(3));var
G=new
Dog(d),n=new
Car();G.bark("ocaml bark");i.log("dog.age: ",G.age);i.log("car.wheels: ",n.wheels);i.log("car.speed: ",n.speed);i.log("car.getSpeed(): ",n.getSpeed());i.log(L,!!n.reads);n[c("reads")]=1;i.log(L,!!n.reads);function
Z(a){var
b=a;for(;;){if(b){var
c=b[2],d=b[1];try{ah(d)}catch(h){}var
b=c;continue}return 0}}Z(aj(0));return}(function(){return this}()));
